# -*- coding: utf-8 -*-
# Use Class with tinker
# Charalambos Themistocleous
# Convertions ARPABET
# 2018


def arpabetIPA(myString):
    aString = myString
    aString = aString.replace("0", "")
    aString = aString.replace("1", "ˈ")
    aString = aString.replace("2", "ˌ")
    aString = aString.replace("AA", "ɑ")
    aString = aString.replace("AE", "æ")
    aString = aString.replace("AH", "ʌ")
    aString = aString.replace("AO", "ɔ")
    aString = aString.replace("AW", "aʊ")
    aString = aString.replace("AX", "ə")
    aString = aString.replace("AXR", "ɚ")
    aString = aString.replace("AY", "aɪ")
    aString = aString.replace("EH", "ɛ")
    aString = aString.replace("ER", "ɝ")
    aString = aString.replace("EY", "eɪ")
    aString = aString.replace("IH", "ɪ")
    aString = aString.replace("IX", "ɨ")
    aString = aString.replace("IY", "i")
    aString = aString.replace("OW", "oʊ")
    aString = aString.replace("OY", "ɔɪ")
    aString = aString.replace("UH", "ʊ")
    aString = aString.replace("UW", "u")
    aString = aString.replace("UX", "ʉ")
    aString = aString.replace("CH", "tʃ")
    aString = aString.replace("DH", "ð")
    aString = aString.replace("DX", "ɾ")
    aString = aString.replace("EL", "l̩")
    aString = aString.replace("EM", "m̩")
    aString = aString.replace("EN", "n̩")
    aString = aString.replace("JH", "dʒ")
    aString = aString.replace("NX", "ŋ")
    aString = aString.replace("NG", "ŋ")
    aString = aString.replace("NX", "ɾ̃")
    aString = aString.replace("SH", "ʃ")
    aString = aString.replace("TH", "θ")
    aString = aString.replace("WH", "ʍ")
    aString = aString.replace("ZH", "ʒ")
    aString = aString.replace("HH", "h")
    aString = aString.replace("B", "b")
    aString = aString.replace("D", "d")
    aString = aString.replace("F", "f")
    aString = aString.replace("G", "ɡ")
    aString = aString.replace("H", "h")
    aString = aString.replace("K", "k")
    aString = aString.replace("L", "l")
    aString = aString.replace("M", "m")
    aString = aString.replace("N", "n")
    aString = aString.replace("P", "p")
    aString = aString.replace("Q", "ʔ")
    aString = aString.replace("R", "ɹ")
    aString = aString.replace("S", "s")
    aString = aString.replace("T", "t")
    aString = aString.replace("V", "v")
    aString = aString.replace("W", "w")
    aString = aString.replace("Y", "j")
    aString = aString.replace("Z", "z")
    return aString
