# -*- coding: utf-8 -*-
# Use Class with tinker
# Charalambos Themistocleous
# Convertions Cypriot Greek
# 2016

def cgLexIPA(myString):
    aString = myString
    aString = aString.replace("Β", "β")
    aString = aString.replace("Γ", "γ")
    aString = aString.replace("Δ", "δ")
    aString = aString.replace("Ζ", "ζ")
    aString = aString.replace("Θ", "θ")
    aString = aString.replace("Κ", "κ")
    aString = aString.replace("Λ", "λ")
    aString = aString.replace("Μ", "μ")
    aString = aString.replace("Ν", "ν")
    aString = aString.replace("Ξ", "ξ")
    aString = aString.replace("Ο", "ο")
    aString = aString.replace("Ό", "ό")
    aString = aString.replace("Π", "π")
    aString = aString.replace("Ρ", "ρ")
    aString = aString.replace("Σ", "σ")
    aString = aString.replace("Τ", "τ")
    aString = aString.replace("Φ", "φ")
    aString = aString.replace("Ψ", "ψ")
    aString = aString.replace("Χ", "x")

    aString = aString.replace("Α", "α")
    aString = aString.replace("Ά", "ά")
    aString = aString.replace("Η", "η")
    aString = aString.replace("Ή", "ή")
    aString = aString.replace("Ι", "ι")
    aString = aString.replace("Ί", "ί")
    aString = aString.replace("Υ", "υ")
    aString = aString.replace("Ύ", "ύ")
    aString = aString.replace("Ε", "ε")
    aString = aString.replace("Έ", "έ")
    aString = aString.replace("Ω", "ω")
    aString = aString.replace("Ώ", "ώ")

    aString = aString.replace("αι", "ε") #Αυτή η σειρά επιτρέπει την απαγόρευση της εφαρμογής του κανόνα σε λέξεις όπως αβαείο γιατί διαφορετικά θα είχα αβαίο > αβέο
    aString = aString.replace("αί", "έ")
    aString = aString.replace("εί", "ί")
    aString = aString.replace("ει", "ι")
    aString = aString.replace("οι", "ι")
    aString = aString.replace("οί", "ί")
    aString = aString.replace("ου", "u")
    aString = aString.replace("ού", "ú")


#extra rules: economy and avoid useless repeditions
    aString = aString.replace("αυγ", "αβγ")
    aString = aString.replace("αυλ", "αβλ")
    aString = aString.replace("αύγ", "άβγ")
    aString = aString.replace("αύλ", "αβλ")
    aString = aString.replace("ευτ", "εφτ")
    aString = aString.replace("εύτ", "έφτ")
    aString = aString.replace("ευκ", "εφκ")
    aString = aString.replace("εύκ", "έφκ")
    aString = aString.replace("ευπ", "εφπ")
    aString = aString.replace("εύπ", "έφπ")
    aString = aString.replace("ευθ", "εφθ")
    aString = aString.replace("εύθ", "έφθ")
    aString = aString.replace("ευφ", "εφ")
    aString = aString.replace("εύφ", "έφ")
    aString = aString.replace("ευχ", "εφχ")
    aString = aString.replace("εύχ", "έφχ")

    aString = aString.replace("αυτ", "αφτ")
    aString = aString.replace("αύτ", "άφτ")
    aString = aString.replace("αυκ", "αφκ")
    aString = aString.replace("αύκ", "άφκ")
    aString = aString.replace("αυπ", "αφπ")
    aString = aString.replace("αύπ", "άφπ")
    aString = aString.replace("αυθ", "αφθ")
    aString = aString.replace("αύθ", "άφθ")
    aString = aString.replace("αυφ", "αφ")
    aString = aString.replace("αύφ", "άφ")
    aString = aString.replace("αυχ", "αφχ")
    aString = aString.replace("αύχ", "άφχ")
    aString = aString.replace("γκιu", "ɲɉu")
    aString = aString.replace("γκιú", "ɲɉú")
    aString = aString.replace("γκιι", "ɲɉi")
    aString = aString.replace("γκιί", "ɲɉí")
    aString = aString.replace("γκια", "ɲɉa")
    aString = aString.replace("γκιά", "ɲɉá")
    aString = aString.replace("γκιε", "ɲɉe")
    aString = aString.replace("γκιέ", "ɲɉé")
    aString = aString.replace("γκιο", "ɲɉο")
    aString = aString.replace("γκιό", "ɲɉó")
#=======================================
    aString = aString.replace("αυχι", "afci")
    aString = aString.replace("αυχί", "afcí")
    aString = aString.replace("αυχε", "afce")
    aString = aString.replace("αυχέ", "afcé")
    aString = aString.replace("ευχι", "efci")
    aString = aString.replace("ευχί", "efcí")
    aString = aString.replace("ευχε", "efce")
    aString = aString.replace("ευχέ", "efcé")
#=======================================
    aString = aString.replace("κσια", "kʃa")
    aString = aString.replace("κσιά", "kʃá")
    aString = aString.replace("κσιε", "kʃe")
    aString = aString.replace("κσιέ", "kʃé")
    aString = aString.replace("κσιι", "kʃi")
    aString = aString.replace("κσιί", "kʃí")
    aString = aString.replace("κσιο", "kʃο")
    aString = aString.replace("κσιό", "kʃó")
    aString = aString.replace("κσιu", "kʃu")
    aString = aString.replace("κσιú", "kʃú")
#========================================
    aString = aString.replace("πσιu", "pʃu")
    aString = aString.replace("πσιú", "pʃú")
    aString = aString.replace("πσιι", "pʃi")
    aString = aString.replace("πσιί", "pʃí")

    aString = aString.replace("πσια", "pʃa")
    aString = aString.replace("πσιά", "pʃá")
    aString = aString.replace("πσιε", "pʃe")
    aString = aString.replace("πσιέ", "pʃé")
    aString = aString.replace("πσιο", "pʃο")
    aString = aString.replace("πσιό", "pʃó")
#========================================
    aString = aString.replace("ππιú", "pcʰːú")
    aString = aString.replace("ππιί", "pcʰːí")
    aString = aString.replace("ππιά", "pcʰːá")
    aString = aString.replace("ππιέ", "pcʰːé")
    aString = aString.replace("ππιό", "pcʰːó")
#========================================
    aString = aString.replace("τσ̌ιu", "t͡ʃu")
    aString = aString.replace("τσ̌ιú", "t͡ʃú")
    aString = aString.replace("τσ̌ιι", "t͡ʃi")
    aString = aString.replace("τσ̌ιί", "t͡ʃí")
    aString = aString.replace("τσ̌ια", "t͡ʃa")
    aString = aString.replace("τσ̌ιά", "t͡ʃá")
    aString = aString.replace("τσ̌ιε", "t͡ʃe")
    aString = aString.replace("τσ̌ιέ", "t͡ʃé")
    aString = aString.replace("τσ̌ιο", "t͡ʃο")
    aString = aString.replace("τσ̌ιό", "t͡ʃó")
#======================================
    aString = aString.replace("τζ̌ιu", "t͡ʃu")
    aString = aString.replace("τζ̌ιú", "t͡ʃú")
    aString = aString.replace("τζ̌ιι", "t͡ʃi")
    aString = aString.replace("τζ̌ιί", "t͡ʃí")
    aString = aString.replace("τζ̌ια", "t͡ʃa")
    aString = aString.replace("τζ̌ιά", "t͡ʃá")
    aString = aString.replace("τζ̌ιε", "t͡ʃe")
    aString = aString.replace("τζ̌ιέ", "t͡ʃé")
    aString = aString.replace("τζ̌ιο", "t͡ʃο")
    aString = aString.replace("τζ̌ιό", "t͡ʃó")
#======================================
    aString = aString.replace("ndια", "ɲɉa")
    aString = aString.replace("ndιά", "ɲɉá")
    aString = aString.replace("ndιε", "ɲɉe")
    aString = aString.replace("ndιέ", "ɲɉé")
    aString = aString.replace("ndιο", "ɲɉο")
    aString = aString.replace("ndιό", "ɲɉó")
    aString = aString.replace("ndιu", "ɲɉu")
    aString = aString.replace("ndιú", "ɲɉú")
#========================================
    aString = aString.replace("δκια", "θca")
    aString = aString.replace("δκιά", "θcá")
    aString = aString.replace("δκιε", "θce")
    aString = aString.replace("δκιέ", "θcé")
    aString = aString.replace("δκιο", "θcο")
    aString = aString.replace("δκιό", "θcó")
    aString = aString.replace("δκιu", "θcu")
    aString = aString.replace("δκιú", "θcú")
#======================================
    aString = aString.replace("θκια", "θca")
    aString = aString.replace("θκιά", "θcá")
    aString = aString.replace("θκιε", "θce")
    aString = aString.replace("θκιέ", "θcé")
    aString = aString.replace("θκιο", "θcο")
    aString = aString.replace("θκιό", "θcó")
    aString = aString.replace("θκιu", "θcu")
    aString = aString.replace("θκιú", "θcú")
#=====================================
    aString = aString.replace("λλιu", "ʎːu")
    aString = aString.replace("λλιú", "ʎːú")
    aString = aString.replace("λλιι", "ʎːi")
    aString = aString.replace("λλιί", "ʎːí")
    aString = aString.replace("λλια", "ʎːa")
    aString = aString.replace("λλιά", "ʎːá")
    aString = aString.replace("λλιε", "ʎːe")
    aString = aString.replace("λλιέ", "ʎːé")
    aString = aString.replace("λλιο", "ʎːο")
    aString = aString.replace("λλιό", "ʎːó")
#======================================

    aString = aString.replace("γκι", "ɲɉi")
    aString = aString.replace("γκί", "ɲɉí")
    aString = aString.replace("γκε", "ɲɉe")
    aString = aString.replace("γκέ", "ɲɉé")
#=======================================

    aString = aString.replace("γγι", "ɲɉi")
    aString = aString.replace("γγί", "ɲɉí")
    aString = aString.replace("γγε", "ɲɉe")
    aString = aString.replace("γγέ", "ɲɉé")
#======================================
    aString = aString.replace("θια", "θca")
    aString = aString.replace("θιά", "θcá")
    aString = aString.replace("θιε", "θce")
    aString = aString.replace("θιέ", "θcé")
    aString = aString.replace("θιι", "θci")
    aString = aString.replace("θιί", "θcí")
    aString = aString.replace("θιο", "θcο")
    aString = aString.replace("θιό", "θcó")
    aString = aString.replace("θιu", "θcu")
    aString = aString.replace("θιú", "θcú")
#=====================================
    aString = aString.replace("φια", "fca")
    aString = aString.replace("φιά", "fcá")
    aString = aString.replace("φιε", "fce")
    aString = aString.replace("φιέ", "fcé")
    aString = aString.replace("φιι", "fci")
    aString = aString.replace("φιί", "fcí")
    aString = aString.replace("φιο", "fcο")
    aString = aString.replace("φιό", "fcó")
    aString = aString.replace("φιu", "fcu")
    aString = aString.replace("φιú", "fcú")
#=====================================
    aString = aString.replace("κια", "cʰːa")
    aString = aString.replace("κιά", "cʰːá")
    aString = aString.replace("κιε", "cʰːe")
    aString = aString.replace("κιέ", "cʰːé")
    aString = aString.replace("κιι", "cʰːi")
    aString = aString.replace("κιί", "cʰːí")
    aString = aString.replace("κιο", "cʰːο")
    aString = aString.replace("κιό", "cʰːó")
    aString = aString.replace("κιu", "cʰːu")
    aString = aString.replace("κιú", "cʰːú")
#=====================================
    aString = aString.replace("πια", "pca")
    aString = aString.replace("πιά", "pcá")
    aString = aString.replace("πιε", "pce")
    aString = aString.replace("πιέ", "pcé")
    aString = aString.replace("πιι", "pci")
    aString = aString.replace("πιί", "pcí")
    aString = aString.replace("πιο", "pcο")
    aString = aString.replace("πιό", "pcó")
    aString = aString.replace("πιu", "pcu")
    aString = aString.replace("πιú", "pcú")
#======================================
    aString = aString.replace("ντζ̌", "ndʒ")
    aString = aString.replace("ντσ", "nts")
    aString = aString.replace("ντζ", "ndz")
    aString = aString.replace("ρτσ", "ɾ̣ts")
#======================================
    aString = aString.replace("σ̌ια", "ʃa")
    aString = aString.replace("σ̌ιά", "ʃá")
    aString = aString.replace("σ̌ιε", "ʃe")
    aString = aString.replace("σ̌ιέ", "ʃé")
    aString = aString.replace("σ̌ιι", "ʃi")
    aString = aString.replace("σ̌ιί", "ʃí")
    aString = aString.replace("σ̌ιο", "ʃο")
    aString = aString.replace("σ̌ιό", "ʃó")
    aString = aString.replace("σ̌ιu", "ʃu")
    aString = aString.replace("σ̌ιú", "ʃú")
#=====================================
    aString = aString.replace("τια", "tia")
    aString = aString.replace("τιά", "tcá")
    aString = aString.replace("τιε", "tie")
    aString = aString.replace("τιέ", "tcé")
    aString = aString.replace("τιι", "tii")
    aString = aString.replace("τιί", "tcí")
    aString = aString.replace("τιο", "tiο")
    aString = aString.replace("τιό", "tcó")
    aString = aString.replace("τιu", "tiu")
    aString = aString.replace("τιú", "tcú")
#======================================
    aString = aString.replace("βια", "fca")
    aString = aString.replace("βιά", "fcá")
    aString = aString.replace("βιε", "fce")
    aString = aString.replace("βιέ", "fcé")
    aString = aString.replace("βιο", "fcο")
    aString = aString.replace("βιό", "fcó")
    aString = aString.replace("βιu", "fcu")
    aString = aString.replace("βιú", "fcú")
#======================================
    aString = aString.replace("bια", "bia")
    aString = aString.replace("bιά", "bcá")
    aString = aString.replace("bιε", "bce")
    aString = aString.replace("bιέ", "bcé")
    aString = aString.replace("bιο", "bcο")
    aString = aString.replace("bιό", "bcó")
    aString = aString.replace("bιu", "bcu")
    aString = aString.replace("bιú", "bcú")
#======================================
    aString = aString.replace("δια", "ðia")
    aString = aString.replace("διά", "θcá")
    aString = aString.replace("διε", "ðie")
    aString = aString.replace("διέ", "θcé")
    aString = aString.replace("διο", "ðiο")
    aString = aString.replace("διό", "θcó")
    aString = aString.replace("διu", "ðiu")
    aString = aString.replace("διú", "θcú")

#======================================
    aString = aString.replace("ζ̌ια", "ʒːa")
    aString = aString.replace("ζ̌ιά", "ʒːá")
    aString = aString.replace("ζ̌ιε", "ʒːe")
    aString = aString.replace("ζ̌ιέ", "ʒːé")
    aString = aString.replace("ζ̌ιο", "ʒːο")
    aString = aString.replace("ζ̌ιό", "ʒːó")
    aString = aString.replace("ζ̌ιu", "ʒːu")
    aString = aString.replace("ζ̌ιú", "ʒːú")
#======================================
    aString = aString.replace("ρια", "ɾia") # Η περίπτωση του ρ ανκαι μοιάζει με το πιο πάνω δεν είναι από ότι φαίνεται το ι διατηρεί την ανεξαρτησία του και δεν συμπροφέρεται.
    aString = aString.replace("ριά", "ɾ̣ká")
    aString = aString.replace("ριε", "ɾie")
    aString = aString.replace("ριέ", "ɾ̣cé")
    aString = aString.replace("ριο", "ɾio")
    aString = aString.replace("ριό", "ɾ̣kó")
    aString = aString.replace("ριu", "ɾiu")
    aString = aString.replace("ριú", "ɾ̣kú")
#======================================


#======================================
    aString = aString.replace("μια", "mɲa")
    aString = aString.replace("μιά", "mɲá")
    aString = aString.replace("μιε", "mɲe")
    aString = aString.replace("μιέ", "mɲé")
    aString = aString.replace("μιο", "mɲο")
    aString = aString.replace("μιό", "mɲó")
    aString = aString.replace("μιu", "mɲu")
    aString = aString.replace("μιú", "mɲú")
#======================================
    aString = aString.replace("για", "ʝa")
    aString = aString.replace("γιά", "ʝá")
    aString = aString.replace("γιε", "ʝe")
    aString = aString.replace("γιέ", "ʝé")
    aString = aString.replace("γιι", "ʝi")
    aString = aString.replace("γιί", "ʝí")
    aString = aString.replace("γιο", "ʝο")
    aString = aString.replace("γιό", "ʝó")
    aString = aString.replace("γιu", "ʝu")
    aString = aString.replace("γιú", "ʝú")

#=====================================
    aString = aString.replace("λιu", "ʎːu")
    aString = aString.replace("λιú", "ʎːú")
    aString = aString.replace("λιι", "ʎːi")
    aString = aString.replace("λιί", "ʎːí")
    aString = aString.replace("λια", "ʎːa")
    aString = aString.replace("λιά", "ʎːá")
    aString = aString.replace("λιε", "ʎːe")
    aString = aString.replace("λιέ", "ʎːé")
    aString = aString.replace("λιο", "ʎːο")
    aString = aString.replace("λιό", "ʎːó")
#=====================================
    aString = aString.replace("νιu", "ɲːu")
    aString = aString.replace("νιú", "ɲːú")
    aString = aString.replace("νιι", "ɲːi")
    aString = aString.replace("νιί", "ɲːí")
    aString = aString.replace("νια", "ɲːa")
    aString = aString.replace("νιά", "ɲːá")
    aString = aString.replace("νιε", "ɲːe")
    aString = aString.replace("νιέ", "ɲːé")
    aString = aString.replace("νιό", "ɲːó")
    aString = aString.replace("νιο", "ɲːο")
#=====================================
    aString = aString.replace("χχι", "çːi")
    aString = aString.replace("χχί", "çːi")
    aString = aString.replace("χχε", "çːe")
    aString = aString.replace("χχέ", "çːé")
#=====================================
    aString = aString.replace("χιu", "çu")
    aString = aString.replace("χιú", "çú")
    aString = aString.replace("χιι", "çi")
    aString = aString.replace("χιί", "çí")
    aString = aString.replace("χια", "ça")
    aString = aString.replace("χιά", "çá")
    aString = aString.replace("χιε", "çe")
    aString = aString.replace("χιέ", "çé")
    aString = aString.replace("χιο", "çο")
    aString = aString.replace("χιό", "çó")



    aString = aString.replace("κκι", "cʰːi")
    aString = aString.replace("κκί", "cʰːí")
    aString = aString.replace("κκε", "cʰːe")
    aString = aString.replace("κκέ", "cʰːé")

#      aString = aString.replace("λλι", "ʎːi")
#      aString = aString.replace("λλί", "ʎːí")
#      aString = aString.replace("λλε", "ʎːe")
#      aString = aString.replace("λλέ", "ʎːé")


    aString = aString.replace("βγί", "φκί")


    aString = aString.replace("βγ", "φκ")
    aString = aString.replace("βκ", "φκ")
    aString = aString.replace("γκ", "ŋg")
    aString = aString.replace("γγ", "ŋg")
    aString = aString.replace("γι", "ʝi")
    aString = aString.replace("γί", "ʝí")
    aString = aString.replace("γε", "ʝe")
    aString = aString.replace("γέ", "ʝé")
    aString = aString.replace("κι", "ci")
    aString = aString.replace("κί", "cí")
    aString = aString.replace("κε", "ce")
    aString = aString.replace("κέ", "cé")
    aString = aString.replace("χι", "çi")
    aString = aString.replace("χί", "çi")
    aString = aString.replace("χε", "çe")
    aString = aString.replace("χέ", "çé")
    aString = aString.replace("τζ̌", "t͡ʃ")
    aString = aString.replace("τσ", "ts")
    aString = aString.replace("αυ", "av")
    aString = aString.replace("αύ", "áv")
    aString = aString.replace("ευ", "ev")
    aString = aString.replace("εύ", "év")
    aString = aString.replace("γγ", "γκ")
    aString = aString.replace("ντ", "nd")
    aString = aString.replace("μπ", "mb")
    aString = aString.replace("γχ", "xː") #χρειάζομαι περισσότερους κανόνες τους έβαλα κάτω από ΔΦΑ σε ΔΦΑ


    aString = aString.replace("ω", "ο")
    aString = aString.replace("ώ", "ó")
    aString = aString.replace("η", "ι")
    aString = aString.replace("ή", "ί")
    aString = aString.replace("υ", "ι")
    aString = aString.replace("ύ", "ί")
    aString = aString.replace("ξ̌", "κσ̌")
    aString = aString.replace("ξ", "κσ")
    aString = aString.replace("ψ̌", "πσ̌")
    aString = aString.replace("ψ", "πσ")

    aString = aString.replace("ϊ", "i")
    aString = aString.replace("ΐ", "í")
    aString = aString.replace("ϋ", "i")
    aString = aString.replace("ΰ", "í")


# TODO check: The following part was commented for a reason

    aString = aString.replace("ιέ", "é")    #to eixa se comments giat?
    aString = aString.replace("ιό", "jó")
    aString = aString.replace("ιά", "já")
    aString = aString.replace("ιε", "je")
    aString = aString.replace("ιο", "jo")
    aString = aString.replace("ια", "ja")
    aString = aString.replace("ιu", "ju")
    aString = aString.replace("ιú", "jú")
#

    aString = aString.replace("β", "v")
    aString = aString.replace("γ", "ɣ")
    aString = aString.replace("δ", "ð")
    aString = aString.replace("ζ̌", "ʒː")
    aString = aString.replace("ζ", "zː")
    aString = aString.replace("θ", "θ")
    aString = aString.replace("κ", "k")
    aString = aString.replace("λ", "l")
    aString = aString.replace("μ", "m")
    aString = aString.replace("ν", "n")
    aString = aString.replace("π", "p")
    aString = aString.replace("ρ", "ɾ")
    aString = aString.replace("σ̌", "ʃ")
    aString = aString.replace("σ", "s")
    aString = aString.replace("ς̌", "ʃ")
    aString = aString.replace("ς", "s")
    aString = aString.replace("τ", "t")
    aString = aString.replace("φ", "f")
    aString = aString.replace("χ", "x")

    aString = aString.replace("α", "a")
    aString = aString.replace("ά", "á")
    aString = aString.replace("ι", "i")
    aString = aString.replace("ί", "í")
    aString = aString.replace("ο", "o")
    aString = aString.replace("ό", "ó")
    aString = aString.replace("ε", "e")
    aString = aString.replace("έ", "é")
    aString = aString.replace("ω", "o")
    aString = aString.replace("ώ", "ó")

    aString = aString.replace("tt", "tʰː")
    aString = aString.replace("kk", "kʰː")
    aString = aString.replace("cc", "cʰː")
    aString = aString.replace("pp", "pʰː")
    aString = aString.replace("ss", "sː")
    aString = aString.replace("θθ", "θː")
    aString = aString.replace("ll", "lː")
    aString = aString.replace("mm", "mː")
    aString = aString.replace("nn", "nː")
    aString = aString.replace("rr", "r:")
    aString = aString.replace("ff", "fː")
    aString = aString.replace("xx", "xː")
    aString = aString.replace("ʃʃ", "ʃː")
    aString = aString.replace("ʒʒ", "ʒː")

    aString = aString.replace("np", "nb")
    aString = aString.replace("nd", "nd")
    aString = aString.replace("sv", "zv")
    aString = aString.replace("sɣ", "zɣ")
    aString = aString.replace("sð", "zð")
    aString = aString.replace("sm", "zm")
    aString = aString.replace("sn", "zn")
    aString = aString.replace("sd", "zd")
    aString = aString.replace("sb", "zb")
    aString = aString.replace("sg", "zg")
    aString = aString.replace("sr", "zr")

    aString = aString.replace("nk", "ŋg")
    aString = aString.replace("ng", "ŋg")

    aString = aString.replace("nc", "ŋɉ")
    aString = aString.replace("nc", "ŋɉ")

    aString = aString.replace("ɾt", "ṛt")
    aString = aString.replace("ɾk", "ṛk")
    aString = aString.replace("ɾc", "ṛc")
    aString = aString.replace("ɾp", "ṛp")
    aString = aString.replace("ɾθ", "ṛθ")



    aString = aString.replace("mf", "fː")
    aString = aString.replace("mv", "vː")

    aString = aString.replace("ntz", "nd͡ʒ")
    aString = aString.replace("tz", "t͡ʃ")

    aString = aString.replace("ki","ci")
    aString = aString.replace("kí","ci")
    aString = aString.replace("ke", "ce")
    aString = aString.replace("ké", "cé")

    aString = aString.replace("-", "")
    aString = aString.replace("'", "")
    aString = aString.replace("’", "")
    aString = aString.replace("", "")
    aString = aString.replace(",", "")
    aString = aString.replace(".", "")
    aString = aString.replace("?", "")
    aString = aString.replace("@", "")
    aString = aString.replace("#", "")
    aString = aString.replace("$", "")
    aString = aString.replace("%", "")
    aString = aString.replace("^", "")
    aString = aString.replace("&", "")
    aString = aString.replace("*", "")
    aString = aString.replace("(", "")
    aString = aString.replace(")", "")
    aString = aString.replace("+", "")
    aString = aString.replace("=", "")
    aString = aString.replace("_", "")
    aString = aString.replace("1", "")
    aString = aString.replace("2", "")
    aString = aString.replace("3", "")
    aString = aString.replace("4", "")
    aString = aString.replace("5", "")
    aString = aString.replace("6", "")
    aString = aString.replace("7", "")
    aString = aString.replace("8", "")
    aString = aString.replace("9", "")
    aString = aString.replace("0", "")
    aString = aString.replace("~", "")
    aString = aString.replace("`", "")
    aString = aString.replace("ikoʝéɲː", "ikoʝéni")
    aString = aString.replace("ɾaθcófon", "ɾaθcófon")
    aString = aString.replace("θcóti", "ðióti")
    return aString
