# -*- coding: utf-8 -*-
# Use Class with tinker
# Charalambos Themistocleous
# Convertions Standard Modern Greek
# 2016


def grLexIPA(myString):
    aString = myString
    aString = aString.replace("Β", "β")
    aString = aString.replace("Γ", "γ")
    aString = aString.replace("Δ", "δ")
    aString = aString.replace("Ζ", "ζ")
    aString = aString.replace("Θ", "θ")
    aString = aString.replace("Κ", "κ")
    aString = aString.replace("Λ", "λ")
    aString = aString.replace("Μ", "μ")
    aString = aString.replace("Ν", "ν")
    aString = aString.replace("Ξ", "ξ")
    aString = aString.replace("Ο", "ο")
    aString = aString.replace("Ο", "ό")
    aString = aString.replace("Π", "π")
    aString = aString.replace("Ρ", "ρ")
    aString = aString.replace("Σ", "σ")
    aString = aString.replace("Τ", "τ")
    aString = aString.replace("Φ", "φ")
    aString = aString.replace("Ψ", "ψ")
    aString = aString.replace("Χ", "x")

    aString = aString.replace("Α", "α")
    aString = aString.replace("Ά", "ά")
    aString = aString.replace("Η", "η")
    aString = aString.replace("Ή", "ή")
    aString = aString.replace("Ι", "ι")
    aString = aString.replace("Ί", "ί")
    aString = aString.replace("Υ", "υ")
    aString = aString.replace("Ύ", "ύ")
    aString = aString.replace("Ε", "ε")
    aString = aString.replace("Έ", "έ")
    aString = aString.replace("Ω", "ω")
    aString = aString.replace("Ώ", "ώ")

    #extra rules: economy and avoid useless repeditions
    aString = aString.replace("αυγ", "αβγ")
    aString = aString.replace("αυλ", "αβλ")
    aString = aString.replace("αύγ", "άβγ")
    aString = aString.replace("αύλ", "αβλ")
    aString = aString.replace("ευτ", "εφτ")
    aString = aString.replace("εύτ", "έφτ")
    aString = aString.replace("ευκ", "εφκ")
    aString = aString.replace("εύκ", "έφκ")
    aString = aString.replace("ευπ", "εφπ")
    aString = aString.replace("εύπ", "έφπ")
    aString = aString.replace("ευθ", "εφθ")
    aString = aString.replace("εύθ", "έφθ")
    aString = aString.replace("ευφ", "εφ")
    aString = aString.replace("εύφ", "έφ")
    aString = aString.replace("ευχ", "εφχ")
    aString = aString.replace("εύχ", "έφχ")

    aString = aString.replace("αυτ", "αφτ")
    aString = aString.replace("αύτ", "άφτ")
    aString = aString.replace("αυκ", "αφκ")
    aString = aString.replace("αύκ", "άφκ")
    aString = aString.replace("αυπ", "αφπ")
    aString = aString.replace("αύπ", "άφπ")
    aString = aString.replace("αυθ", "αφθ")
    aString = aString.replace("αύθ", "άφθ")
    aString = aString.replace("αυφ", "αφ")
    aString = aString.replace("αύφ", "άφ")
    aString = aString.replace("αυχ", "αφχ")
    aString = aString.replace("αύχ", "άφχ")

    aString = aString.replace("αυ", "av")
    aString = aString.replace("αύ", "áv")
    aString = aString.replace("ευ", "ev")
    aString = aString.replace("εύ", "év")
    aString = aString.replace("γγ", "γκ")
    aString = aString.replace("ντζ", "nτζ")
    aString = aString.replace("ντσ", "nτσ")
    aString = aString.replace("ντ", "d")
    aString = aString.replace("μπ", "b")
    aString = aString.replace("αι", "ε") #Αυτή η σειρά επιτρέπει την απαγόρευση της εφαρμογής του κανόνα σε λέξεις όπως αβαείο γιατί διαφορετικά θα είχα αβαίο > αβέο
    aString = aString.replace("αί", "έ")
    aString = aString.replace("εί", "ί")
    aString = aString.replace("ει", "ι")
    aString = aString.replace("οι", "ι")
    aString = aString.replace("οί", "ί")
    aString = aString.replace("ου", "u")
    aString = aString.replace("ού", "ú")
    aString = aString.replace("σσ", "σ")
    aString = aString.replace("θθ", "θ")
    aString = aString.replace("κκ", "κ")
    aString = aString.replace("λλ", "λ")
    aString = aString.replace("μμ", "μ")
    aString = aString.replace("ππ", "π")
    aString = aString.replace("ρρ", "ρ")
    aString = aString.replace("ττ", "τ")
    aString = aString.replace("φφ", "φ")
    aString = aString.replace("χχ", "χ")
    aString = aString.replace("ω", "ο")
    aString = aString.replace("ώ", "ó")
    aString = aString.replace("η", "ι")
    aString = aString.replace("ή", "ί")
    aString = aString.replace("υ", "ι")
    aString = aString.replace("ύ", "ί")
    aString = aString.replace("ξ", "κσ")
    aString = aString.replace("ψ", "πσ")
    aString = aString.replace("ϊ", "i")
    aString = aString.replace("ΐ", "í")
    aString = aString.replace("ϋ", "i")
    aString = aString.replace("ΰ", "í")


#end of extra rule

    #aString = aString.replace("ποιού", "piú")
    #aString = aString.replace("ποιοί", "pií")
    #aString = aString.replace("ποιώ", "pió")
    #aString = aString.replace("ποιέ", "pié")
    #aString = aString.replace("ποιά", "piá")

#========================================================

    aString = aString.replace("γκιu", "ɉu")
    aString = aString.replace("γκιú", "ɉú")
    aString = aString.replace("γκιι", "ɉi")
    aString = aString.replace("γκιί", "ɉí")
    aString = aString.replace("γκια", "ɉa")
    aString = aString.replace("γκιά", "ɉá")
    aString = aString.replace("γκιε", "ɉe")
    aString = aString.replace("γκιέ", "ɉé")
    aString = aString.replace("γκιο", "ɉο")
    aString = aString.replace("γκιό", "ɉó")
#=======================================
    aString = aString.replace("αυχι", "afçi")
    aString = aString.replace("αυχί", "afçí")
    aString = aString.replace("αυχε", "afçe")
    aString = aString.replace("αυχέ", "afçé")
    aString = aString.replace("ευχι", "efçi")
    aString = aString.replace("ευχί", "efçí")
    aString = aString.replace("ευχε", "efçe")
    aString = aString.replace("ευχέ", "efçé")
#=======================================
    aString = aString.replace("κσια", "ksça")
    aString = aString.replace("κσιά", "ksçá")
    aString = aString.replace("κσιε", "ksçe")
    aString = aString.replace("κσιέ", "ksçé")
    aString = aString.replace("κσιι", "ksçi")
    aString = aString.replace("κσιί", "ksçí")
    aString = aString.replace("κσιο", "ksçο")
    aString = aString.replace("κσιό", "ksçó")
    aString = aString.replace("κσιu", "ksçu")
    aString = aString.replace("κσιú", "ksçú")
#========================================
    aString = aString.replace("πσιu", "psçu")
    aString = aString.replace("πσιú", "psçú")
    aString = aString.replace("πσιι", "psçi")
    aString = aString.replace("πσιί", "psçí")
    aString = aString.replace("πσια", "psça")
    aString = aString.replace("πσιά", "psçá")
    aString = aString.replace("πσιε", "psçe")
    aString = aString.replace("πσιέ", "psçé")
    aString = aString.replace("πσιο", "psçο")
    aString = aString.replace("πσιό", "psçó")
    #========================================
    aString = aString.replace("τσιu", "tsçu")
    aString = aString.replace("τσιú", "tsçú")
    aString = aString.replace("τσιι", "tsçi")
    aString = aString.replace("τσιί", "tsçí")
    aString = aString.replace("τσια", "tsça")
    aString = aString.replace("τσιά", "tsçá")
    aString = aString.replace("τσιε", "tsçe")
    aString = aString.replace("τσιέ", "tsçé")
    aString = aString.replace("τσιο", "tsçο")
    aString = aString.replace("τσιό", "tsçó")
#======================================
    aString = aString.replace("θια", "θça")
    aString = aString.replace("θιά", "θçá")
    aString = aString.replace("θιε", "θçe")
    aString = aString.replace("θιέ", "θçé")
    aString = aString.replace("θιι", "θçi")
    aString = aString.replace("θιί", "θçí")
    aString = aString.replace("θιο", "θçο")
    aString = aString.replace("θιό", "θçó")
    aString = aString.replace("θιu", "θçu")
    aString = aString.replace("θιú", "θçú")
#=====================================
    aString = aString.replace("φια", "fça")
    aString = aString.replace("φιά", "fçá")
    aString = aString.replace("φιε", "fçe")
    aString = aString.replace("φιέ", "fçé")
    aString = aString.replace("φιι", "fçi")
    aString = aString.replace("φιί", "fçí")
    aString = aString.replace("φιο", "fçο")
    aString = aString.replace("φιό", "fçó")
    aString = aString.replace("φιu", "fçu")
    aString = aString.replace("φιú", "fçú")
#=====================================
    aString = aString.replace("κια", "cça")
    aString = aString.replace("κιά", "cçá")
    aString = aString.replace("κιε", "cçe")
    aString = aString.replace("κιέ", "cçé")
    aString = aString.replace("κιι", "cçi")
    aString = aString.replace("κιί", "cçí")
    aString = aString.replace("κιο", "cçο")
    aString = aString.replace("κιό", "cçó")
    aString = aString.replace("κιu", "cçu")
    aString = aString.replace("κιú", "cçú")
#=====================================
    aString = aString.replace("πια", "pça")
    aString = aString.replace("πιά", "pçá")
    aString = aString.replace("πιε", "pçe")
    aString = aString.replace("πιέ", "pçé")
    aString = aString.replace("πιι", "pçi")
    aString = aString.replace("πιί", "pçí")
    aString = aString.replace("πιο", "pçο")
    aString = aString.replace("πιό", "pçó")
    aString = aString.replace("πιu", "pçu")
    aString = aString.replace("πιú", "pçú")
#=====================================
    aString = aString.replace("σια", "sça")
    aString = aString.replace("σιά", "sçá")
    aString = aString.replace("σιε", "sçe")
    aString = aString.replace("σιέ", "sçé")
    aString = aString.replace("σιι", "sçi")
    aString = aString.replace("σιί", "sçí")
    aString = aString.replace("σιο", "sçο")
    aString = aString.replace("σιό", "sçó")
    aString = aString.replace("σιu", "sçu")
    aString = aString.replace("σιú", "sçú")
#=====================================
    aString = aString.replace("τια", "tça")
    aString = aString.replace("τιά", "tçá")
    aString = aString.replace("τιε", "tçe")
    aString = aString.replace("τιέ", "tçé")
    aString = aString.replace("τιι", "tçi")
    aString = aString.replace("τιί", "tçí")
    aString = aString.replace("τιο", "tçο")
    aString = aString.replace("τιό", "tçó")
    aString = aString.replace("τιu", "tçu")
    aString = aString.replace("τιú", "tçú")
#======================================
    aString = aString.replace("βια", "vʝa")
    aString = aString.replace("βιά", "vʝá")
    aString = aString.replace("βιε", "vʝe")
    aString = aString.replace("βιέ", "vʝé")
    aString = aString.replace("βιο", "vʝο")
    aString = aString.replace("βιό", "vʝó")
    aString = aString.replace("βιu", "vʝu")
    aString = aString.replace("βιú", "vʝú")
#======================================
    aString = aString.replace("bια", "bʝa")
    aString = aString.replace("bιά", "bʝá")
    aString = aString.replace("bιε", "bʝe")
    aString = aString.replace("bιέ", "bʝé")
    aString = aString.replace("bιο", "bʝο")
    aString = aString.replace("bιό", "bʝó")
    aString = aString.replace("bιu", "bʝu")
    aString = aString.replace("bιú", "bʝú")
#======================================
    aString = aString.replace("δια", "ðʝa")
    aString = aString.replace("διά", "ðʝá")
    aString = aString.replace("διε", "ðʝe")
    aString = aString.replace("διέ", "ðʝé")
    aString = aString.replace("διο", "ðʝο")
    aString = aString.replace("διό", "ðʝó")
    aString = aString.replace("διu", "ðʝu")
    aString = aString.replace("διú", "ðʝú")
#======================================
    aString = aString.replace("dια", "dʝa")
    aString = aString.replace("dιά", "dʝá")
    aString = aString.replace("dιε", "dʝe")
    aString = aString.replace("dιέ", "dʝé")
    aString = aString.replace("dιο", "dʝο")
    aString = aString.replace("dιό", "dʝó")
    aString = aString.replace("dιu", "dʝu")
    aString = aString.replace("dιú", "dʝú")
#======================================
    aString = aString.replace("ζια", "zʝa")
    aString = aString.replace("ζιά", "zʝá")
    aString = aString.replace("ζιε", "zʝe")
    aString = aString.replace("ζιέ", "zʝé")
    aString = aString.replace("ζιο", "zʝο")
    aString = aString.replace("ζιό", "zʝó")
    aString = aString.replace("ζιu", "zʝu")
    aString = aString.replace("ζιú", "zʝú")
#======================================
    aString = aString.replace("ρια", "rʝa") # Η περίπτωση του ρ ανκαι μοιάζει με το πιο πάνω δεν είναι από ότι φαίνεται το ι διατηρεί την ανεξαρτησία του και δεν συμπροφέρεται.
    aString = aString.replace("ριά", "rʝá")
    aString = aString.replace("ριε", "rʝe")
    aString = aString.replace("ριέ", "rʝé")
    aString = aString.replace("ριο", "rʝο")
    aString = aString.replace("ριό", "rʝó")
    aString = aString.replace("ριu", "rʝu")
    aString = aString.replace("ριú", "rʝú")
#======================================
    aString = aString.replace("μια", "mɲa")
    aString = aString.replace("μιά", "mɲá")
    aString = aString.replace("μιε", "mɲe")
    aString = aString.replace("μιέ", "mɲé")
    aString = aString.replace("μιο", "mɲο")
    aString = aString.replace("μιό", "mɲó")
    aString = aString.replace("μιu", "mɲu")
    aString = aString.replace("μιú", "mɲú")
#======================================
    aString = aString.replace("για", "ʝa")
    aString = aString.replace("γιά", "ʝá")
    aString = aString.replace("γιε", "ʝe")
    aString = aString.replace("γιέ", "ʝé")
    aString = aString.replace("γιι", "ʝi")
    aString = aString.replace("γιί", "ʝí")
    aString = aString.replace("γιο", "ʝο")
    aString = aString.replace("γιό", "ʝó")
    aString = aString.replace("γιu", "ʝu")
    aString = aString.replace("γιú", "ʝú")
#=====================================
    aString = aString.replace("λιu", "ʎu")
    aString = aString.replace("λιú", "ʎú")
    aString = aString.replace("λιι", "ʎi")
    aString = aString.replace("λιί", "ʎí")
    aString = aString.replace("λια", "ʎa")
    aString = aString.replace("λιά", "ʎá")
    aString = aString.replace("λιε", "ʎe")
    aString = aString.replace("λιέ", "ʎé")
    aString = aString.replace("λιο", "ʎο")
    aString = aString.replace("λιό", "ʎó")
#=====================================
    aString = aString.replace("νιu", "ɲu")
    aString = aString.replace("νιú", "ɲú")
    aString = aString.replace("νιι", "ɲi")
    aString = aString.replace("νιί", "ɲí")
    aString = aString.replace("νια", "ɲa")
    aString = aString.replace("νιά", "ɲá")
    aString = aString.replace("νιε", "ɲe")
    aString = aString.replace("νιέ", "ɲé")
    aString = aString.replace("νιό", "ɲó")
    aString = aString.replace("νιο", "ɲο")
#=====================================
    aString = aString.replace("χιu", "çu")
    aString = aString.replace("χιú", "çú")
    aString = aString.replace("χιι", "çi")
    aString = aString.replace("χιί", "çí")
    aString = aString.replace("χια", "ça")
    aString = aString.replace("χιά", "çá")
    aString = aString.replace("χιε", "çe")
    aString = aString.replace("χιέ", "çé")
    aString = aString.replace("χιο", "çο")
    aString = aString.replace("χιό", "çó")



    aString = aString.replace("γχ", "ŋx") #χρειάζομαι περισσότερους κανόνες τους έβαλα κάτω από ΔΦΑ σε ΔΦΑ


    aString = aString.replace("γκι", "ɉi")
    aString = aString.replace("γκί", "ɉí")
    aString = aString.replace("γκε", "ɉe")
    aString = aString.replace("γκέ", "ɉé")
    aString = aString.replace("γκ", "g")
    aString = aString.replace("νν", "n")
    aString = aString.replace("γι", "ʝi")
    aString = aString.replace("γί", "ʝí")
    aString = aString.replace("γε", "ʝe")
    aString = aString.replace("γέ", "ʝé")
    aString = aString.replace("κι", "ci")
    aString = aString.replace("κί", "cí")
    aString = aString.replace("κε", "ce")
    aString = aString.replace("κέ", "cé")
    aString = aString.replace("τσ", "ts")
    aString = aString.replace("χι", "çi")
    aString = aString.replace("χί", "çí")
    aString = aString.replace("χε", "çe")
    aString = aString.replace("χέ", "çé")

    #aString = aString.replace("ιέ", "jé")
    #aString = aString.replace("ιό", "jó")
    #aString = aString.replace("ιά", "já")
    #aString = aString.replace("ιε", "je")
    #aString = aString.replace("ιο", "jo")
    #aString = aString.replace("ια", "ja")
    #aString = aString.replace("ιu", "ju")
    #aString = aString.replace("ιú", "jú")



    aString = aString.replace("β", "v")
    aString = aString.replace("γ", "ɣ")
    aString = aString.replace("δ", "ð")
    aString = aString.replace("ζ", "z")
    aString = aString.replace("θ", "θ")
    aString = aString.replace("κ", "k")
    aString = aString.replace("λ", "l")
    aString = aString.replace("μ", "m")
    aString = aString.replace("ν", "n")
    aString = aString.replace("ξ", "ks")
    aString = aString.replace("π", "p")
    aString = aString.replace("ρ", "r")
    aString = aString.replace("σ", "s")
    aString = aString.replace("ς", "s")
    aString = aString.replace("τ", "t")
    aString = aString.replace("φ", "f")
    aString = aString.replace("ψ", "ps")
    aString = aString.replace("χ", "x")

    aString = aString.replace("α", "a")
    aString = aString.replace("ά", "á")
    aString = aString.replace("ι", "i")
    aString = aString.replace("ί", "í")
    aString = aString.replace("ο", "o")
    aString = aString.replace("ό", "ó")
    aString = aString.replace("ε", "e")
    aString = aString.replace("έ", "é")
    aString = aString.replace("ω", "o")
    aString = aString.replace("ώ", "ó")


    aString = aString.replace("np", "b")
    aString = aString.replace("nd", "d")
    aString = aString.replace("sv", "zv")
    aString = aString.replace("sɣ", "zɣ")
    aString = aString.replace("sð", "zð")
    aString = aString.replace("sm", "zm")
    aString = aString.replace("sn", "zn")
    aString = aString.replace("sd", "zd")
    aString = aString.replace("sb", "zb")
    aString = aString.replace("sg", "zg")
    aString = aString.replace("sr", "zr")

    aString = aString.replace("nk", "ŋk")
    aString = aString.replace("ng", "ŋg")

    aString = aString.replace("nc", "ŋc")
    aString = aString.replace("nc", "ŋc")

    aString = aString.replace("mf", "ɱf")
    aString = aString.replace("mv", "ɱv")
    return aString
